# Generated by Django 4.0.3 on 2022-03-31 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_property_agent_propertyimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-price']},
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propertyimages', to='core.property'),
        ),
        migrations.CreateModel(
            name='AgentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='core/agent/images')),
                ('Agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentimages', to='core.agent')),
            ],
        ),
    ]
